name: scirag
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.47.0=hadc24fc_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=he02047a_1
  - openssl=3.3.2=hb9d3cd8_0
  - pip=24.2=pyh8b19718_1
  - python=3.10.15=h4a871b0_2_cpython
  - readline=8.2=h8228510_1
  - setuptools=75.1.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.44.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - accelerate==1.0.1
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.8.0
      - async-timeout==4.0.3
      - attrs==24.2.0
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - datasets==3.0.2
      - dill==0.3.8
      - distro==1.9.0
      - exceptiongroup==1.2.2
      - filelock==3.13.1
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.26.1
      - idna==3.4
      - jinja2==3.1.3
      - jiter==0.8.2
      - joblib==1.4.2
      - jsonlines==4.0.0
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.2.1
      - numpy==1.26.3
      - openai==1.63.2
      - packaging==24.1
      - pandas==2.2.3
      - peft==0.13.2
      - pillow==10.2.0
      - propcache==0.2.0
      - psutil==6.1.0
      - pyarrow==17.0.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - regex==2024.9.11
      - requests==2.32.3
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - sentence-transformers==3.2.1
      - six==1.16.0
      - sniffio==1.3.1
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - tokenizers==0.20.1
      - torch==2.1.0+cu118
      - torchaudio==2.1.0+cu118
      - torchvision==0.16.0+cu118
      - tqdm==4.66.5
      - transformers==4.46.0
      - triton==2.1.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==1.26.13
      - xxhash==3.5.0
      - yarl==1.16.0
